[phases.setup]
nixPkgs = [
  "nodejs_20",
  "ffmpeg",
  "fontconfig",
  "freetype",
  "harfbuzz",
  "dejavu_fonts",
  "python3",
  "python3Packages.pip"
]

[phases.install]
cmds = [
  "npm install",
  "pip install rembg pillow"
]

[start]
cmd = "node server.js"
